server:
  port: 8085

spring:
  security:
    user:
      name: user
      password: password
      roles: USER
  datasource:
    url: jdbc:postgresql://localhost:5432/greetingsdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        connection:
          url: jdbc:postgresql://localhost:5432/greetingsdb
          username: postgres
          password: postgres
#        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.security: TRACE
